version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: bank-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bankdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
