version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: kind_torvalds
    ports:
      - "5673:5672"
      - "15673:15672"
      - "61614:61613"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    command: >
      bash -c "
      rabbitmq-plugins enable rabbitmq_stomp rabbitmq_web_stomp;
      rabbitmq-server"
  mysql:
    image: mysql:8.0
    container_name: bank-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bankdb
      MYSQL_USER: chatuser
      MYSQL_PASSWORD: chatpass
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
  rabbitmq_data:
  rabbitmq_logs:


